apps/api/urls.py
from django.urls import path
from apps.api.views import *

app_name = "api"

urlpatterns = [
    path('v1/task/', TaskViewSets.as_view(), name="v1_task_sets"),
    path('v1/task/<int:pk>/', TaskUpdateView.as_view(), name="v1_task_update"),
    path('v1/category/', CategoryViewSets.as_view(), name="v1_category_sets"),
    path('v1/tag/', TagViewSets.as_view(), name="v1_tag_sets"),
]

apps/task/urls.py
from django.urls import path
from apps.task.views import *

app_name = "task"

urlpatterns = [
    path('category/', CategoryListCreateView.as_view(), name="category_list"),
    # path('category/<int:pk>', CategoryDetailView.as_view(), name="category_detail"),
    path('tag/', TagListView.as_view(), name="tag_list"),
    path('', TaskListView.as_view(), name="task_list"),
    path('<int:pk>/', TaskDetailView.as_view(), name="task_detail"),
    path('create/', TaskCreateView.as_view(), name="task_create"),
    path('create/category/', CategoryCreateView.as_view(), name="category_create"),
    path('create/tag/', TagCreateView.as_view(), name="tag_create"),
]

apps/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from apps.users.views import RegisterView, LoginView

app_name = "users"

urlpatterns = [
    path('register/', RegisterView.as_view(), name="register"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("apps.users.urls")),
    path('task/', include("apps.task.urls")),
    path('api/', include("apps.api.urls")),
    path('accounts/', include('allauth.urls')),
]

apps/api/models.py
from django.db import models

# Create your models here.

apps/task/models/category.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

apps/task/models/tag.py
from django.db import models

class Tag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

apps/task/models/task.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    STATUS_CHOICES = [
        ("Pending", "待處理"),
        ("In progress", "處理中"),
        ("Done", "完成"),
        ("Delete", "刪除"),
    ]
    title = models.CharField(max_length=20)
    # 原import <modelName>, 更改成使用字串, 避免循環依賴
    # category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="task")
    category = models.ForeignKey("Category", on_delete=models.CASCADE, related_name="tasks")
    tags = models.ManyToManyField("Tag", related_name='tasks', blank=True) # null = True(default)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="Pending")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tasks")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
    @classmethod
    def get_status_choices(self):
        return self.STATUS_CHOICES

apps/task/forms.py
from django import forms
from apps.task.models import Category, Tag

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        labels = {
                "name": 'Create a new category: ',
        }

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = '__all__'
        labels = {
                "name": 'Create a new Tag: ',
        }

apps/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        # widgets = {
        #     "password": forms.PasswordInput(attrs={
        #         'placeholder': '密碼長度區間6-20個字元',
        #     }),
        # }

apps/api/views.py
from django.shortcuts import render
from apps.task.models import *
from apps.api.serializers import *
from rest_framework import status
from rest_framework import generics
from rest_framework.response import Response

# List
class TaskViewSets(generics.ListCreateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer

class TaskUpdateView(generics.RetrieveUpdateAPIView):
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    def post(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance, data = request.data, partial = True)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status=status.HTTP_200_OK)

class CategoryViewSets(generics.ListCreateAPIView):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

class TagViewSets(generics.ListCreateAPIView):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

apps/task/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import FormMixin
from django.urls import reverse_lazy
from apps.task.models import Category, Tag, Task
from apps.task.forms import CategoryForm, TagForm
# Create your views here.
class CategoryListView(generic.ListView):
    model = Category

class CategoryListCreateView(FormMixin, generic.ListView):
    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('task:category_list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class CategoryCreateView(generic.CreateView):
    model = Category
    fields = ['name']

class TagListView(FormMixin, generic.ListView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('task:tag_list')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            form.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

class TaskListView(generic.ListView):
    model = Task

class TagCreateView(generic.CreateView):
    model = Tag
    fields = ['name']

class TaskDetailView(generic.DetailView):
    model = Task
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["status_choices"] = Task.get_status_choices()
        return context

class TaskCreateView(generic.CreateView):
    model = Task
    fields = ['title', 'category', 'tags', 'status']
    success_url = reverse_lazy("task:task_list")
    def form_valid(self, form):
        # 將當前使用者設為 owner
        form.instance.owner = self.request.user
        return super().form_valid(form)

apps/users/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth import views, forms
from apps.users.forms import RegisterForm
# Create your views here.

class RegisterView(generic.CreateView):
    form_class = RegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")

class LoginView(views.LoginView):
    form_class = forms.AuthenticationForm
    template_name = "users/login.html"

apps/task/templates/task/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% block navbar %}
      {% include "task/navbar.html" %}
    {% endblock %}
    <div class="container">
      {% block container %}
      {% endblock %}
    </div>
    

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->

    {% load static %}
    <script src="{% static '/task/js/main.js' %}"></script>
  </body>
</html>

apps/task/templates/task/category_detail.html
{% extends "task/base.html" %}
{% block container %}
    {% if object %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ object.name }}</h5>
                <!-- <h6 class="card-subtitle mb-2 text-muted">{{ object.created_at }}</h6> -->
                <!-- <p class="card-text">{{ object.content }}</p> -->
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ object.created_at }}</small>
            </div>
        </div>
    {% endif %}
{% endblock %}

apps/task/templates/task/category_list.html
{% extends "task/base.html" %}
{% block container %}
    <h1>Categories</h1>
    {% load crispy_forms_tags %}
    {% if form %}
        <form class="form-inline" method="post">
            {% csrf_token %}
            {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    {% endif %}
    <br/>
    {% if category_list %}
        <div class="list-group">
            {% for category in category_list %}
                <a href="#" class="list-group-item list-group-item-action">{{ category.name }}</a>
            {% endfor %}
        </div>  
    {% endif %}
{% endblock %}

apps/task/templates/task/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar scroll</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarScroll">
    <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">Task</a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="{% url 'task:task_list' %}">Task List</a></li>
          <li><a class="dropdown-item" href="{% url 'task:task_create' %}">Create Task</a></li>
        </ul>
      </li>
      <li class="nav-item"><a class="nav-link" href="{% url 'task:category_list' %}">分類</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'task:tag_list' %}">標籤</a></li>
      
    </ul>
    {% if not user.is_authenticated %}
    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
    <a class="nav-link" href="{% url 'users:login' %}">Login</a>
    <!-- <a class="nav-link" href="">Logout</a> -->
    {% else %}
    <span class="navbar-text">{{ user.username }}</span>
    <form class="d-flex" method="post" action="{% url 'users:logout' %}">
      {% csrf_token %}
      <button class="btn btn-outline-danger" type="submit">Logout</button>
    </form>
    {% endif %}
  </div>
</nav>

apps/task/templates/task/tag_list.html
{% extends "task/base.html" %}
{% block container %}
    <h1>Tags</h1>
    {% load crispy_forms_tags %}
    {% if form %}
        <form class="form-inline" method="post">
            {% csrf_token %}
            {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    {% endif %}
    <br/>
    {% if tag_list %}
        <div class="list-group">
            {% for tag in tag_list %}
                <a href="#" class="list-group-item list-group-item-action">{{ tag.name }}</a>
            {% endfor %}
        </div>
        
    {% endif %}
{% endblock %}

apps/task/templates/task/task_detail.html
{% extends "task/base.html" %}
{% block container %}
    {% if object %}
        <div class="card" style="width: 18rem;" data-id="{{ object.id }}">
            <div class="card-body">
                <h5 class="card-title">{{ object.title }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ object.category }}</h6>
                <p class="card-text">
                <h6>
                    {% for tag in object.tags.all %}
                    <span class="badge badge-primary">{{ tag }}</span>
                    {% endfor %}
                </h6>
                <select id="status">
                    {% for key, label in status_choices %}
                    <option value="{{ key }}" {% if object.status == key %}selected{% endif %}>{{ label }}</option>
                    {% endfor %}
                </select>
                <br/>
                <small class="text-muted">上次更新: {{ object.updated_at }}</small>
                </p>
            </div>
            <div class="card-footer">
                <small class="text-muted">{{ object.created_at }}</small>
                <br/>
                
            </div>
        </div>
    {% endif %}
{% endblock %}

apps/task/templates/task/task_form.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
    <h1>Create Task</h1>
    {% if form %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Save">
        </form>
    {% endif %}
{% endblock %}

apps/task/templates/task/task_list.html
{% extends "task/base.html" %}
{% block container %}
    <h1>Tasks</h1>
    {% if task_list %}
        <div class="list-group">
            {% for task in task_list %}
                <a href="{% url 'task:task_detail' task.id %}" class="list-group-item list-group-item-action">{{ task.title }}</a>
            {% endfor %}
        </div>
        
    {% endif %}
{% endblock %}

apps/users/templates/users/login.html
{% extends "task/base.html" %}
{% load socialaccount %}
{% load crispy_forms_tags %}
{% block container %}
    <h1>Login</h1>
    {% if form %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="btn btn-primary" type="submit">Login</button>
            {% get_providers as socialaccount_providers %}
            {% for provider in socialaccount_providers %}
                <a href="{% provider_login_url provider.id %}" class="btn btn-link" role="button" aria-pressed="true">Log in with {{ provider.name }}</a>
            {% endfor %}
        </form>
    {% endif %}
{% endblock %}

apps/users/templates/users/register.html
{% extends "task/base.html" %}
{% load crispy_forms_tags %}
{% block container %}
    <h1>Register</h1>
    {% if form %}
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
{% endblock %}